export enum MovieGenreEnum {
    Comedy= 'Comedy',
    Short= 'Short',
    Crime= 'Crime',
    Drama= 'Drama',
    Mystery= 'Mystery',
    Documentary= 'Documentary',
    History= 'History',
    Fantasy= 'Fantasy',
    Western= 'Western',
    Family= 'Family',
    Romance= 'Romance',
    Adventure= 'Adventure',
    War= 'War',
    Animation= 'Animation',
    Horror= 'Horror',
    Action= 'Action',
    Sport= 'Sport',
    Thriller= 'Thriller'
}